### ISSUE TITLE
error-handler-plugin does not work on Mule runtime 4.4

### ISSUE THREAD

**Issue by hemant-pandey** [mulesoft-catalyst/error-handler-plugin#10]
Hello Team, 

I am working on project with Mule 4.4 and getting error while deploying the application. Same code is working file on Mule 4.3.

Here is the Error which I can see in console:-

_Message        : Invalid configuration found for component [set-attributes]: 
 No [script] nor [resource] parameters were provided, but one is required
Element        : mule_db_operationFlow @ mule_db_operation:mule_db_operation.xml:22
Element DSL      : (None)
Error type      : (None)
FlowStack       : (None)
 (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)_

Thanks,
Hemant

**Comment by abpatel-fi** [comment]
Weare running into the same exact issue.
Is this connector/code base even actively being maintained anymore? The last commit I see is Aug 2020

**Comment by biswa-mohanty** [comment]
this is due to a breaking change in the runtime wrt XML SDK. this has already been raised to the product team.

**Comment by tulasikamodula** [comment]
This is fixed with the latest update to studio.

**Comment by kishan2512** [comment]
I dont think, It is fixed. I am getting same error with latest version of studio with runtime 4.4.x.

**Comment by amran-ahmadSFDC** [comment]
Looks like it is working now. I am able to run it both in Studio and CH with 4.4.0 now. Can anyone confirm?

**Comment by kishan2512** [comment]
Yes, It is working as expected now when I have updated to latest studio-runtime.

**Comment by firstrustbank** [comment]
What studio-runtime version is working for you? I am on 7.11 and still getting this error

**Comment by AvinashT93** [comment]
how to check and where to update latest studio-runtime.

**Comment by AvinashT93** [comment]
Any steps

**Comment by sf-charles** [comment]
Closed as addressed by update to Mule runtime.  This is available in latest Studio.
